const VISUAL_BY_ICON_KEY: Readonly<Record<string, string>> = {
  fridge: '/appliances/3d/fridge.webp',
  ac: '/appliances/3d/ac.webp',
  washer: '/appliances/3d/washer.webp',
  dishwasher: '/appliances/3d/dishwasher.webp',
  oven: '/appliances/3d/oven.webp',
  toaster: '/appliances/3d/toaster.webp',
  kettle: '/appliances/3d/kettle.webp',
  tv: '/appliances/3d/tv.webp',
  pc: '/appliances/3d/pc.webp',
  lighting: '/appliances/3d/lighting.webp',
  vacuum: '/appliances/3d/vacuum.webp',
  dryer: '/appliances/3d/dryer.webp',
  heater: '/appliances/3d/heater.webp',
  microwave: '/appliances/3d/microwave.webp',
  iron: '/appliances/3d/iron.webp',
  hairdryer: '/appliances/3d/hairdryer.webp',
  freezer: '/appliances/3d/freezer.webp',
  blender: '/appliances/3d/blender.webp',
  coffee: '/appliances/3d/coffee.webp',
  fan: '/appliances/3d/fan.webp',
  router: '/appliances/3d/router.webp',
  gameconsole: '/appliances/3d/gameconsole.webp',
  hood: '/appliances/3d/hood.webp',
  stove: '/appliances/3d/stove.webp',
  waterdispenser: '/appliances/3d/waterdispenser.webp',
  airfryer: '/appliances/3d/airfryer.webp',
  spaceheater: '/appliances/3d/spaceheater.webp',
  dehumidifier: '/appliances/3d/dehumidifier.webp',
  airpurifier: '/appliances/3d/airpurifier.webp',
  robotvacuum: '/appliances/3d/robotvacuum.webp',
  hairstraightener: '/appliances/3d/hairstraightener.webp',
  shaver: '/appliances/3d/shaver.webp',
  breadmaker: '/appliances/3d/breadmaker.webp',
  pressurecooker: '/appliances/3d/pressurecooker.webp',
  printer: '/appliances/3d/printer.webp',
  projector: '/appliances/3d/projector.webp',
  smartspeaker: '/appliances/3d/smartspeaker.webp',
  minifridge: '/appliances/3d/minifridge.webp',
  waterpurifier: '/appliances/3d/waterpurifier.webp',
  electricblanket: '/appliances/3d/electricblanket.webp',
  laptop: '/appliances/3d/laptop.webp',
  monitor: '/appliances/3d/monitor.webp',
  soundbar: '/appliances/3d/soundbar.webp',
  mediabox: '/appliances/3d/mediabox.webp',
  mixer: '/appliances/3d/mixer.webp',
  juicer: '/appliances/3d/juicer.webp',
  waterheatertank: '/appliances/3d/waterheatertank.webp',
  handvacuum: '/appliances/3d/handvacuum.webp',
  sewingmachine: '/appliances/3d/sewingmachine.webp',
  aquarium: '/appliances/3d/aquarium.webp',
  evcharger: '/appliances/3d/evcharger.webp',
  lawnmower: '/appliances/3d/lawnmower.webp',
};

export function getApplianceVisualSrc(iconKey: string): string | null {
  return VISUAL_BY_ICON_KEY[iconKey] ?? null;
}
